project:
  type: website
  output-dir: _site

website:
  title: "Diogo Guillen"
  site-url: "https://diogoguillen.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: policy.qmd
        text: Policy & Public Engagement
      - href: talks.qmd
        text: Talks
      - href: cv.qmd
        text: CV
      - href: contact.qmd
        text: Contact
  page-footer:
    left: "Â© {format-date(now(), '%Y')} Diogo Guillen"
    right:
      - icon: github
        href: https://github.com/diogoguillen
      - icon: linkedin
        href: https://www.linkedin.com/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
