project:
  type: website
  output-dir: _site

website:
  title: "Diogo Guillen"
  site-url: "https://diogoguillen.github.io"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: research.qmd
        text: Research
      - href: policy.qmd
        text: Policy & Public
  page-footer:
    left: "Diogo Guillen"
    right:
      - icon: linkedin
        href: https://www.linkedin.com/in/diogo-guillen-4500a071/

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false
    smooth-scroll: true
    link-external-newwindow: true
